alias vi='vim'
alias inkscape='inkscape'
alias op='opencode'
alias chrome='google-chrome-stable --no-sandbox --force-dark-mode --force-device-scale-factor=1.5'


# kbd backlight on low
echo 1 > /sys/class/leds/tpacpi::kbd_backlight/brightness

# console prompt =  user@current relative directory
export PS1='\[\e[32m\]\u@\[\e[38;5;153m\]\W\[\e[0m\]\$ '

# to make inkscape font a readable size
export GDK_DPI_SCALE=1.5

#opencode (not part of core install)
export PATH=/root/.opencode/bin:$PATH

#node (not part of core install)
export PATH=/usr/local/node/bin:$PATH
