syntax on
set number
set t_Co=256
colorscheme pablo

set clipboard=unnamedplus

"nnoremap <C-S-c> <Nop>
"vnoremap <C-S-c> <Nop>
"inoremap <C-S-c> <Nop>
"nnoremap <C-S-v> <Nop>
"vnoremap <C-S-v> <Nop>
"inoremap <C-S-v> <Nop>
