while true; do
    xsetroot -name "BAT: $(cat /sys/class/power_supply/BAT0/capacity 2>/dev/null || echo 'N/A')% $(status=$(cat /sys/class/power_supply/BAT0/status 2>/dev/null || echo 'Unknown'); case $status in Charging|'Not charging') echo "($status)" ;; *) echo "" ;; esac) | $(date +'%F %T')"
    sleep 1
done &

exec dwm
