#!/bin/bash

# help.sh - Display dwm keybindings and shell aliases

# Load aliases from bashrc
source ~/.bashrc

echo "=== dwm KEYBINDINGS (Mod = Super / Caps Lock) ==="
echo ""
echo "  LAUNCHING"
echo "  Mod+Shift+Enter            -> New terminal window (foot)"
echo "  Ctrl+Shift+T               -> New terminal window (foot)"
echo "  Mod+R                      -> dmenu_run (app launcher)"
echo "  Ctrl+Shift+B               -> New Firefox window"
echo ""
echo "  WINDOW MANAGEMENT"
echo "  Mod+Shift+Z                -> Kill current window"
echo "  Mod+Ctrl+Shift+Q           -> Quit dwm"
echo "  Mod+Esc                    -> Lock screen"
echo "  Mod+B                      -> Toggle bar"
echo ""
echo "  LAYOUT"
echo "  Mod+M                      -> Monocle layout"
echo "  Mod+T                      -> Tile layout"
echo "  Mod+F                      -> Float layout"
echo ""
echo "  TAGS"
echo "  Mod+1-9                    -> Switch to tag 1-9"
echo "  Mod+Shift+1-9              -> Move window to tag 1-9"
echo "  Mod+Ctrl+1-9               -> Toggle tag view"
echo "  Mod+Ctrl+Shift+1-9         -> Toggle tag on window"
echo "  Mod+0                      -> Show all tags"
echo "  Mod+Shift+0                -> Tag all windows"
echo "  Mod+Left                   -> Previous tag"
echo "  Mod+Right                  -> Next tag"
echo "  Mod+A                      -> Previous tag (alt)"
echo "  Mod+D                      -> Next tag (alt)"
echo ""
echo "  FOCUS"
echo "  Mod+Down / Mod+S           -> Focus next window"
echo "  Mod+Up   / Mod+W           -> Focus previous window"
echo "  Mod+Shift+Left             -> Move window to previous tag"
echo "  Mod+Shift+Right            -> Move window to next tag"
echo ""
echo "  MONITOR / MASTER"
echo "  Mod+,                      -> Focus previous monitor"
echo "  Mod+.                      -> Focus next monitor"
echo "  Mod+Shift+,                -> Move window to previous monitor"
echo "  Mod+Shift+.                -> Move window to next monitor"
echo "  Mod+]                      -> Increase master area size"
echo "  Mod+[                      -> Decrease master area size"
echo ""
echo "  MEDIA KEYS (hardware keys, no Mod)"
echo "  XF86AudioLowerVolume       -> Volume down"
echo "  XF86AudioRaiseVolume       -> Volume up"
echo "  XF86AudioMute              -> Volume mute"
echo "  XF86MonBrightnessDown      -> Screen brightness down"
echo "  XF86MonBrightnessUp        -> Screen brightness up"
echo "  Shift+XF86MonBrightnessDown  -> Keyboard backlight down"
echo "  Shift+XF86MonBrightnessUp    -> Keyboard backlight up"
echo ""
echo "=== SHELL COMMANDS (from ~/.bashrc) ==="
echo ""
grep '#help:' ~/.bashrc | sed 's/.*#help://' | sort
