#!/bin/sh
exec env \
    MOZ_DISABLE_GMP_SANDBOX=1 \
    MOZ_GMP_PATH=/usr/lib64/mozilla/gmp-widevinecdm:/usr/lib64/firefox/gmp-widevinecdm \
    GTK_THEME=Adwaita:dark \
    MOZ_GTK_TITLEBAR_DECORATION=client \
    /usr/lib64/firefox/firefox "$@"
