Section "InputClass"
    Identifier "touchpad"
    MatchIsTouchpad "on"
    Driver "libinput"
    Option "Tapping" "off"
    Option "ClickMethod" "clickfinger"
    Option "SoftButtonAreas" "0 0 0 0 0 0 0 0"
EndSection