alias vi='vim'
alias inkscape='inkscape & exit'
alias op='opencode'
alias web='/usr/local/bin/chromium-wrapper.sh & exit'
alias f='yad --file & exit'
alias help='/usr/local/bin/help.sh'
alias neofetch='neofetch && echo -e "\nNeed Help? Try the Following: help"'
alias wifi='/usr/local/bin/wifi_rescan.sh'
alias sound='alsamixer'
alias vnc='/usr/local/bin/vnc-picker.sh'
alias llm='/usr/local/bin/llm-wrapper.sh'
alias vpn='/usr/local/bin/nordvpn-run.sh'
alias gc='git commit'
alias gs='git status'
alias gp='git push'
alias ga='git add'

# kbd backlight on low
echo 1 > /sys/class/leds/tpacpi::kbd_backlight/brightness

# console prompt =  user@current relative directory
export PS1='\[\e[32m\]\u@\[\e[38;5;153m\]\W\[\e[0m\]\$ '

# to make inkscape font a readable size
export GDK_DPI_SCALE=1.5

#opencode (not part of core install)
export PATH=/root/.opencode/bin:$PATH

#node (not part of core install)
export PATH=/usr/local/node/bin:$PATH
