#!/bin/sh
selected=$( (echo -e "NETWORK/WIFI\nWEB\nEDITOR"; dmenu_path) | dmenu "$@" | tr '[:upper:]' '[:lower:]' )
case $selected in
    network/wifi|nmtui) st -e nmtui & ;;
    web) google-chrome-stable --no-sandbox --force-dark-mode --force-device-scale-factor=1.5 & ;;
    editor) st -e vim & ;;
    *) [ -n "$selected" ] && $selected & ;;
esac
