#!/bin/bash
# steps/slskd.sh - SOULSEEK DAEMON (slskd)
# Downloads the standalone linux-x64 zip (glibc build for Slackware).

REPO_DIR="${REPO_DIR:-/root/slackware-installer-for-rs}"
LOG_FILE="${LOG_FILE:-/logs/installer.log}"

if [ -f "$REPO_DIR/lib/common.sh" ]; then
    . "$REPO_DIR/lib/common.sh"
fi

echo "*****************************************************"
echo "SOULSEEK DAEMON (slskd)"
echo "*****************************************************"

ok=true

# --- Read keys (if available) ---
SLSKD_VERSION="${SLSKD_VERSION:-0.25.1}"
SLSKD_USERNAME="${SLSKD_USERNAME:-}"
SLSKD_PASSWORD="${SLSKD_PASSWORD:-}"
SLSKD_WEB_PORT="${SLSKD_WEB_PORT:-5030}"
SLSKD_SLSK_PORT="${SLSKD_SLSK_PORT:-50300}"
SLSKD_SHARE_DIR="${SLSKD_SHARE_DIR:-/var/lib/slskd/music}"
SLSKD_DOWNLOAD_DIR="${SLSKD_DOWNLOAD_DIR:-/var/lib/slskd/downloads}"
SLSKD_UID="${SLSKD_UID:-4876}"

# --- Create dedicated system user ---
if ! id -u slskd >/dev/null 2>&1; then
    echo "Creating slskd system user..."
    if ! useradd -r -d /var/lib/slskd -s /sbin/nologin -u "$SLSKD_UID" slskd; then
        echo "ERROR: Failed to create slskd user."
        ok=false
    fi
else
    echo "slskd user already exists."
fi

# --- Create directories ---
if $ok; then
    echo "Creating slskd directories..."
    mkdir -p /opt/slskd /etc/slskd "$SLSKD_SHARE_DIR" "$SLSKD_DOWNLOAD_DIR" || {
        echo "ERROR: Failed to create slskd directories."
        ok=false
    }
fi

# --- Download and extract standalone linux-x64 zip ---
if $ok; then
    SLSKD_ZIP="slskd-${SLSKD_VERSION}-linux-x64.zip"
    SLSKD_URL="https://github.com/slskd/slskd/releases/download/${SLSKD_VERSION}/${SLSKD_ZIP}"

    if [ ! -f "/opt/slskd/slskd" ] || [ "$1" = "--force-download" ]; then
        echo "Downloading slskd v${SLSKD_VERSION} (standalone linux-x64)..."
        if ! curl -fsSL -o "/tmp/${SLSKD_ZIP}" "$SLSKD_URL"; then
            echo "ERROR: Failed to download slskd from $SLSKD_URL"
            ok=false
        fi

        if $ok; then
            echo "Extracting slskd to /opt/slskd..."
            if ! unzip -o "/tmp/${SLSKD_ZIP}" -d /opt/slskd; then
                echo "ERROR: Failed to extract slskd zip."
                ok=false
            fi
            rm -f "/tmp/${SLSKD_ZIP}"
        fi
    else
        echo "slskd already present in /opt/slskd (use --force-download to re-download)."
    fi
fi

# --- Write config ---
if $ok; then
    echo "Writing slskd config to /etc/slskd/slskd.yml..."
    cat > /etc/slskd/slskd.yml << SLSKDEOF
# slskd configuration (generated by slackware-installer-for-rs)
# Web UI: http://<host>:${SLSKD_WEB_PORT}
# Soulseek protocol port: ${SLSKD_SLSK_PORT}

soulseek:
  username: ${SLSKD_USERNAME}
  password: ${SLSKD_PASSWORD}

shares:
  directories:
    - ${SLSKD_SHARE_DIR}

directories:
  downloads: ${SLSKD_DOWNLOAD_DIR}

web:
  port: ${SLSKD_WEB_PORT}
  https:
    disabled: true
  authentication:
    disabled: true

soulseek_port: ${SLSKD_SLSK_PORT}
SLSKDEOF
fi

# --- Write BSD-style init script ---
if $ok; then
    echo "Writing BSD init script for slskd..."
    cat > /etc/rc.d/rc.slskd << 'INITSCRIPT'
#!/bin/bash
# /etc/rc.d/rc.slskd - start/stop Soulseek daemon
SLSKD_USER="slskd"
SLSKD_BIN="/opt/slskd/slskd"
SLSKD_CONFIG="/etc/slskd/slskd.yml"
PIDFILE="/run/slskd.pid"

case "$1" in
    start)
        echo "Starting slskd..."
        if [ -f "$PIDFILE" ] && kill -0 $(cat "$PIDFILE") 2>/dev/null; then
            echo "slskd already running."
        else
            mkdir -p /run/slskd /var/lib/slskd
            chown $SLSKD_USER:$SLSKD_USER /run/slskd /var/lib/slskd 2>/dev/null || true
            su - $SLSKD_USER -s /bin/bash -c "nohup $SLSKD_BIN --config $SLSKD_CONFIG > /dev/null 2>&1 & echo \$! > $PIDFILE"
            echo "slskd started."
        fi
        ;;
    stop)
        echo "Stopping slskd..."
        if [ -f "$PIDFILE" ]; then
            kill $(cat "$PIDFILE") 2>/dev/null || true
            rm -f "$PIDFILE"
        fi
        pkill -u "$SLSKD_USER" 2>/dev/null || true
        ;;
    restart)
        $0 stop
        sleep 1
        $0 start
        ;;
    status)
        if [ -f "$PIDFILE" ] && kill -0 $(cat "$PIDFILE") 2>/dev/null; then
            echo "slskd is running (PID $(cat $PIDFILE))"
        else
            echo "slskd is not running."
        fi
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        ;;
esac
INITSCRIPT
    chmod +x /etc/rc.d/rc.slskd || {
        echo "ERROR: Failed to make init script executable."
        ok=false
    }
fi

# --- Deploy slsk control script ---
if $ok; then
    echo "Deploying slsk control script to /usr/local/bin/slsk..."
    if [ -f "$REPO_DIR/scripts/slsk.sh" ]; then
        cp "$REPO_DIR/scripts/slsk.sh" /usr/local/bin/slsk || { echo "ERROR: Failed to copy slsk script."; ok=false; }
        chmod +x /usr/local/bin/slsk || { echo "ERROR: Failed to chmod slsk script."; ok=false; }
    else
        echo "WARNING: scripts/slsk.sh not found; skipping control script."
    fi
fi

# --- Deploy sudoers ---
echo "Deploying sudoers for slskd access..."
mkdir -p /etc/sudoers.d
cp "$REPO_DIR/dotfiles/sudoers/slskd" /etc/sudoers.d/slskd 2>/dev/null || true
chmod 440 /etc/sudoers.d/slskd 2>/dev/null || true

# --- Enable service via rc.local ---
if $ok; then
    echo "Adding slskd to /etc/rc.d/rc.local for auto-start..."
    if [ -f /etc/rc.d/rc.local ]; then
        if ! grep -q "rc.slskd" /etc/rc.d/rc.local 2>/dev/null; then
            echo "/etc/rc.d/rc.slskd start" >> /etc/rc.d/rc.local
        fi
    fi
fi

if $ok; then
    echo "SUCCESS: slskd v${SLSKD_VERSION} installed."
    echo ""
    echo "  Config:         /etc/slskd/slskd.yml"
    echo "  Binary:         /opt/slskd/slskd"
    echo "  Init:           /etc/rc.d/rc.slskd {start|stop|restart|status}"
    echo "  Web UI:         http://localhost:${SLSKD_WEB_PORT}"
    echo ""
    echo "  IMPORTANT: Edit /etc/slskd/slskd.yml to set your Soulseek username"
    echo "  and password if not already populated from setup.keys.root."
    exit 0
else
    echo "ERROR: slskd setup encountered errors."
    exit 1
fi
